[package]
name = "jj_rewrite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.22.0", features = ["rt", "rt-multi-thread", "macros"] }
serenity = { default-features = false, features = ["client", "gateway", "model", "rustls_backend"], version = "0.11.5" }
dotenv = "0.15.0"
anyhow = "1.0.68"
tracing = "0.1.37"
