[package]
name = "jj_rewrite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.26.0", features = ["rt", "rt-multi-thread", "macros"] }
serenity = { default-features = false, features = ["client", "gateway", "model", "rustls_backend"], version = "0.11.5" }
dotenv = "0.15.0"
tracing = "0.1.37"
reqwest = { version = "0.11.14", features = ["json"] }
serde = "1.0.153"
serde_json = "1.0.94"
serde_derive = "1.0.152"
itertools = "0.10.5"
chrono = "0.4.23"
chrono-tz = "0.8.1"
