version: "3.8"

services:
  bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    env_file: ".env"
    environment:
      - TZ=America/New_York
# Change to local timezone for accturate match days/times, TZ defaults to GMT when unset
